controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [drainy]
    drainy:
      freq: 10.0
      plugin: drainy_controller/DrainyController
      x_gain: 0.8
      y_gain: 0.8
      z_gain: 1.0
      yaw_gain: 1.0
      safety_radius: 1.0 

# controller_node:
#   ros__parameters:
#     use_sim_time: true
#     controller_types: [dummy]
#     dummy:
#       freq: 10.0
#       rt_freq: 10.0 
#       plugin: easynav_controller/DummyController

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [drainy]
    drainy:
      freq: 20.0
      plugin: drainy_localizer/DrainyLocalizer

# localizer_node:
#   ros__parameters:
#     use_sim_time: true
#     localizer_types: [dummy]
#     dummy:
#       rt_freq: 50.0
#       freq: 5.0
#       reseed_freq: 0.1
#       plugin: easynav_localizer/DummyLocalizer
#       cycle_time_nort: 0.01
#       cycle_time_rt: 0.001

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [drainy]
    drainy:
      freq: 0.5 
      plugin: drainy_maps_manager/DrainyMapsManager
      map_path: /home/juanscelyg/ws/drainy_ws/
      map_topic: /genz/local_map
      filter_min: 0.9
      filter_max: 1.1
      max_lenght: 150.0
      resolution: 0.5
      confidence_lenght: 1.0

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [drainy]
    drainy:
      freq: 1.0
      plugin: drainy_planner/DrainyPlanner
      robot_radius: 0.3
      clearance_distance: 0.2

# planner_node:
#   ros__parameters:
#     use_sim_time: true
#     planner_types: [dummy]
#     dummy:
#       freq: 1.0
#       plugin: easynav_planner/DummyPlanner
#       cycle_time_nort: 0.2
#       cycle_time_rt: 0.001

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [rgbd]
    perception_default_frame: odom
    rgbd:
      topic: /depth_camera/points
      type: sensor_msgs/msg/PointCloud2

system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    robot_frame: drainy_0
    robot_footprint_frame: drainy_0
    position_tolerance: 0.5
    angle_tolerance: 0.3